name:                hvilken-lib
version:             0.1.0.0
github:              "cristeahub/hvilken"
license:             BSD3
author:              "Christoffer Tønnessen"
maintainer:          "given@upon.request"
copyright:           "2020 Christoffer Tønnessen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cristeahub/hvilken#readme>

dependencies:
- base >= 4.7 && < 5
- time >= 1.9.3
- process
- hspec >= 2.0

library:
  source-dirs: src

executables:
  hvilken:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hvilken-lib

tests:
  hvilken-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hvilken-lib
