on: [push]

name: build and test

jobs:
  runhaskell:
    name: Run tests
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8.3'
          cabal-version: '3.0.0.0'
      - run: cabal test
