on: [push]

name: build and test

jobs:
  runonmacos:
    name: Test and build for macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
          cabal-version: '3.0.0.0'
      - name: Test
        run: cabal test
      - name: Build
        run: cabal build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /Users/runner/work/hvilken/hvilken/dist-newstyle/build/x86_64-osx/ghc-8.10.7/hvilken-0.1.0.0/x/hvilken/build/hvilken/hvilken

  runonlinux:
    name: Test and build for Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
          cabal-version: '3.0.0.0'
      - name: Test
        run: cabal test
      - name: Build
        run: cabal build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /home/runner/work/hvilken/hvilken/dist-newstyle/build/x86_64-linux/ghc-8.10.7/hvilken-0.1.0.0/x/hvilken/build/hvilken/hvilken
