name: build-and-test

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack test
